version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=djangoapptest
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
